import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { useEffect } from "react";
import "flowbite/dist/flowbite.css"
import Navbar from "./components/ui/NavBar";
import Footer from "./components/ui/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body>

        <main className="grow">

          <Navbar />
          <section className="size-full bg-gray-50 dark:bg-gray-200">
            {children}
          </section>
          <Footer />

        </main>
      </body>
    </html>
  );
}
